### ISSUE TITLE
Clearing local files and setting crashes the app 

### ISSUE THREAD

**Issue by MKrabs** [OpenSauce04/nook-desktop#1]
I just downloaded the program, saw that it downloaded the songs and disabled that.

If i click on "Clear local files and settings" the app crashes.

> Fedora release 38 (Thirty Eight)
> Gnome 44.1
> Wayland
> Nook version 1.0.9 flathub

**Comment by MKrabs** [comment]
Since this is the only active fork of the app, how can I get engaged in helping the developement?

**Comment by OpenSauce04** [comment]
This is intended behavior; The app restarts once the local data has been cleared, even on the official build

**Comment by OpenSauce04** [comment]
> Since this is the only active fork of the app, how can I get engaged in helping the development?

This fork is only intended to be a Linux port of the official build, keeping in lockstep with the features of that version

Therefore, the only contributions that would be appropriate to this fork would be fixing Linux-specific issues with the program that would have no purpose being pushed to the upstream

In all other cases, making a PR to the upstream would be preferable, even if the maintainer has long periods of absence
