### ISSUE TITLE
windowing is bugged

### ISSUE THREAD

**Issue by mikoducky** [OpenSauce04/nook-desktop#3]
Fedora 38 with Gnome 44.3 on Xorg (I believe it happens on Wayland as well)

With this rounded window corners app: https://extensions.gnome.org/extension/5237/rounded-window-corners/ I can see that the window itself is pretty bugged. It doesn't allow resizing, and as mentioned in the original app github, minimize is gone after the last update, even when you have the tray extension installed.

You can see the window constraints when I have my border on.

![Screenshot from 2023-07-23 23-08-37](https://github.com/OpenSauce04/nook-desktop/assets/74574472/43e4101d-93e0-459f-97af-503d9fd4517c)

**Comment by OpenSauce04** [comment]
This is a limitation of how the original app was built. There is a large invisible area under the window. Without upstream changes, this won't change
